<?php

/**
 * @file
 * Common jobiqo graphql alterations and helper functions.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;

/**
 * Implements hook_entity_field_access().
 */
function jobiqo_graphql_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  if ($field_definition
    ->getName() == 'roles' && $operation == 'view') {
    return AccessResult::allowedIf($account->isAuthenticated());
  }
  return AccessResult::neutral();
}
